// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXFvN4B0Dpxpb4y8gCfM2IwrwSNcAyIOU',
    appId: '1:666643783238:web:ce9794313c9af5cf927447',
    messagingSenderId: '666643783238',
    projectId: 'simple-ecom-1e5fc',
    authDomain: 'simple-ecom-1e5fc.firebaseapp.com',
    storageBucket: 'simple-ecom-1e5fc.appspot.com',
    measurementId: 'G-94MLW15344',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9pcwr7pfPUOhTue0hVzFWA8YtGXF5eGQ',
    appId: '1:666643783238:android:c42fa2179cbf823b927447',
    messagingSenderId: '666643783238',
    projectId: 'simple-ecom-1e5fc',
    storageBucket: 'simple-ecom-1e5fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA69uIJ_l5EGckfh-O9PVdbtXCTmiCcohA',
    appId: '1:666643783238:ios:9cc74f22dd245a60927447',
    messagingSenderId: '666643783238',
    projectId: 'simple-ecom-1e5fc',
    storageBucket: 'simple-ecom-1e5fc.appspot.com',
    iosBundleId: 'com.tukitaki.project.simpleFirebaseStorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA69uIJ_l5EGckfh-O9PVdbtXCTmiCcohA',
    appId: '1:666643783238:ios:79ca3b5875e39f1e927447',
    messagingSenderId: '666643783238',
    projectId: 'simple-ecom-1e5fc',
    storageBucket: 'simple-ecom-1e5fc.appspot.com',
    iosBundleId: 'com.tukitaki.project.simpleFirebaseStorage.RunnerTests',
  );
}
